import React from 'react';
import NavHeader from '@/components/common/navHeader';
import SearchBar from './search-bar/SearchBar';
import Head from 'next/head';

export default function HotelPage() {
  return (
    <>
      <Head>
        <title>Hotel List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <NavHeader />
        <section>
          <div>
            <SearchBar />
          </div>
        </section>
      </div>
    </>
  );
}
