import scss from '@/pages/prod/index.module.scss';
import Head from 'next/head';
import DefaultLayout from '@/components/layout/default';
import Breadcrumb from '@/pages/prod/breadcrumb';
import DetailImg from './detailImg';

export default function Detail() {
  return (
    <>
      <Head>
        <title>Detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <h1 className=''>狗的飼料</h1>
        <Breadcrumb />
        <div className='dFlex'>
        <DetailImg />
        </div>
      </main>
    </>
  )
}
Detail.layout = DefaultLayout;
