import scss from '@/pages/prod/index.module.scss';
import Head from 'next/head';
import DefaultLayout from '@/components/layout/default';
import Section from '@/pages/prod/section';
import Breadcrumb from '@/pages/prod/breadcrumb';
import Select from '@/pages/prod/select';
import style from '@/styles/style.module.scss';
import Aside from '@/pages/prod/aside';
import ProductGrid from './productGrid';

export default function ProductList() {
  return (
    <>
      <Head>
        <title>productList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.container}>
        <Section />
        <div
          className={[
            style.dFlex,
            scss.justifyContentBetween,
            scss.margin,
          ].join(' ')}
        >
          <Breadcrumb />
          <Select />
        </div>
        <div className={[style.dFlex, scss.gap, scss.mt].join(' ')}>
          <Aside />
          <ProductGrid />
        </div>
      </main>
    </>
  );
}
ProductList.layout = DefaultLayout;
