import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/router';
import Head from 'next/head';
import scss from '@/pages/article/content.module.scss';
import DefaultLayout from '@/components/layout/default';
import TitleAction from './commonItem/titleAction';
import ArticleContent from './contentItems/articleContent';
import ArtiAside from './commonItem/aside';
import ReplyArea from './contentItems/replyArea';
import ReplyBlock from './contentItems/replyBlock';
import UserCard from './contentItems/userCard'
import AsideRwd from './commonItem/asideRwd';
import UserAction from './commonItem/userAction';

export default function Content() {
    return (
        <>
            <Head>
                <title>文章內容</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={scss.mainbg}>
                <main className="container" style={{ paddingTop: '40px' }}>
                    <div className={scss.userActionRwd}>
                        <UserAction />
                    </div>
                    <TitleAction />

                    <div className={[scss.mainArea].join()}>
                        <div className={scss.rwdAside}>
                            <ArtiAside />
                        </div>

                        <div className={scss.contentArea}>
                            <ArticleContent />
                            <ReplyArea />
                            <ReplyBlock />
                            <AsideRwd />
                        </div>
                        <UserCard />
                    </div>
                </main>
            </div>
        </>
    )
}

Content.layout = DefaultLayout;
