import React,{useState,useEffect} from 'react'
import Head from 'next/head';
import scss from '@/pages/article/content.module.scss';
import DefaultLayout from '@/components/layout/default';
import TitleAction from './titleAction';
import ArticleContent from './articleContent';
import ArtiAside from './aside';
import ReplyArea from './replyArea';
import ReplyBlock from './replyBlock';
import UserCard from './userCard'
import AsideRwd from './asideRwd';

export default function Content() {
    const [content, setContent] = useState({})
    useEffect(() => {
      fetch('http://localhost:3001/api/articleContent/31')
        .then(response => response.json())
        .then(data => {
          if (data.status === 'success') {
            setContent(data.content[0])
          }
        }).catch(error => console.log(error.message))
    }, [])
    return (
        <>
            <Head>
                <title>文章內容</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={scss.mainbg}>
                <main className="container" style={{ paddingTop: '40px' }}>
                    <TitleAction />

                    <div className={[scss.mainArea].join()}>
                        <div className={scss.rwdAside}>
                            <ArtiAside />
                        </div>

                        <div className={scss.contentArea}>
                            <ArticleContent key={content.id} content={content}/>
                            <ReplyArea />
                            <ReplyBlock />
                            <AsideRwd />
                        </div>
                        <UserCard />
                    </div>
                </main>
            </div>
        </>
    )
}

Content.layout = DefaultLayout;
