import { useState, useEffect, useRef } from 'react';
import scss from '@/pages/article/editArticle.module.scss'
import axios from 'axios';
import Editor from './editor';
import Head from 'next/head';
import DefaultLayout from '@/components/layout/default';
import { Router, useRouter } from 'next/router';


export default function EditArticle() {
  const [title, setTitle] = useState('')
  const [content, setContent] = useState('')
  const [sortOptions, setSortOptions] = useState([])
  const [selectedSort, setSelectedSort] = useState('0')
  const router = useRouter()

  useEffect(() => {
    fetch('http://localhost:3001/api/sort')
      .then(response => response.json())
      .then(data => {
        if (data.status === 'success') {
          setSortOptions(data.sorts)
        }
      }).catch(error => console.log(error.message))
  }, [])

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (selectedSort === '0') {
      alert('請選擇文章分類');
      return;
    }
    try {
      // 從 content 中提取所有的 imageId
      const parser = new DOMParser();
      const doc = parser.parseFromString(content, 'text/html');
      const imageElements = doc.getElementsByTagName('img');

      const imageIds = Array.from(imageElements).map(img => {
        const src = img.getAttribute('src');
        const match = src.match(/articleImage-(\d+)-\d+.png/);
        return match ? parseInt(match[1]) : null;
      }).filter(id => id !== null);
      const response = await axios.post('http://localhost:3001/api/createArticle', { title, content, sort: selectedSort, imageIds });
      console.log('Article created:', response.data)
      alert('文章發表成功')
      router.push(`/article`)
    } catch (error) {
      console.error('Error creating article:', error)
    }
  }

  return (
    <>
      <Head>
        <title>發表文章</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={scss.mainbg}>
        <div className={`container ${scss.creatForm}`}>
          <div className={scss.bread}>
            <h4>home/討論區/發表文章</h4>
          </div>
          <form onSubmit={handleSubmit} className={` ${scss.formArea}`}>
            <input
              className={scss.artiTitle}
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="文章標題"
              required
            />
            <select className={scss.artiSort} value={selectedSort} onChange={(e) => setSelectedSort(e.target.value)} required>
              <option value="0">選擇分類</option>
              {sortOptions.map(sortitem => (
                <option key={sortitem.id} value={sortitem.id}>{sortitem.sort}</option>
              ))}
            </select>
            <Editor content={content} setContent={setContent} editorHei="400px" />
            <div>
              <button className={scss.postBtn} type="submit">發布文章</button>
            </div>
          </form>
        </div>

      </div>

    </>

  );
}

CreateArticle.layout = DefaultLayout;