import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import DefaultLayout from '@/components/layout/default';
import scss from '@/pages/article/index.module.scss';
import UserAction from './userAction';
import ArtiAside from './aside';
import ArticleList from './articleList';
import PageControl from './pageControl';
import ArticleContent from './articleContent';
import ReplyArea from './replyArea';
import ReplyBlock from './replyBlock';
import Image from 'next/image';

export default function Index() {
  return (
    <>
      <Head>
        <title>文章列表</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={scss.mainbg}>
        <main className="container" style={{ paddingTop: '40px' }}>
          <UserAction />

          <div className={[scss.mainArea].join()}>
            <ArtiAside />
            <div className={scss.contentArea}>
              <ArticleContent />
              <ReplyArea />
              <ReplyBlock/>
            </div>
            
            {/* <ArticleList /> */}
            <PageControl />
          </div>
        </main>
      </div>
    </>
  );
}

Index.layout = DefaultLayout;
