import Head from 'next/head';
import Link from 'next/link';
import style from '@/styles/style.module.scss';
import FddBtn from '@/components/buttons/fddBtn';
import hs from './home.module.scss';
import { IconContext } from 'react-icons';
import { FaArrowRightLong } from 'react-icons/fa6';
import { IoAddCircle } from 'react-icons/io5';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={hs.bgLight}>
        <section>
          <h1 className={hs.h1}>這是開發用的首頁</h1>
          <h2 className={hs.h2}>通往各開發中頁面的捷徑</h2>
          <div className={style.container}>
            <div className={[hs.linkPanel, style.row, style.g3].join(' ')}>
              <div className={[style.col6, style.col_lg4].join(' ')}>
                <Link href="/homepage">首頁</Link>
              </div>
              <div className={[style.col6, style.col_lg4].join(' ')}>
                <Link href="/prod">商品</Link>
              </div>
              <div className={[style.col6, style.col_lg4].join(' ')}>
                <Link href="">會員</Link>
              </div>
              <div className={[style.col6, style.col_lg4].join(' ')}>
                <Link href="">旅館</Link>
              </div>
              <div className={[style.col6, style.col_lg4].join(' ')}>
                <Link href="">文章</Link>
              </div>
              <div className={[style.col6, style.col_lg4].join(' ')}>
                <Link href="">課程</Link>
              </div>
              <div className={[style.col6, style.col_lg4].join(' ')}>
                <Link href="/test/">測試用</Link>
              </div>
            </div>
          </div>
        </section>
        <section className={style.container}>
          <h1 className={hs.h1}>開發指南</h1>
          <article>
            <h2 className={hs.h2}>可以使用的樣式</h2>
            <p style={{ textAlign: 'center' }}>
              <IconContext.Provider
                value={{ style: { verticalAlign: 'middle' } }}
              >
                Bootstrap 的語法
                <FaArrowRightLong />
                Fundodo 專案的語法
              </IconContext.Provider>
            </p>
            <div className={hs.dlBox}>
              <IconContext.Provider
                value={{ style: { verticalAlign: 'middle' } }}
              >
                <dl className={hs.instructionList}>
                  <dt>背景、文字顏色</dt>
                  <dd>
                    <span>.bg-primary</span>
                    <FaArrowRightLong />
                    <code>.bgPrimary</code>
                  </dd>
                  <dd>
                    <span>.bg-secondary</span>
                    <FaArrowRightLong />
                    <code>.bgSecondary</code>
                  </dd>
                  <dd>
                    <span>.text-primary</span>
                    <FaArrowRightLong />
                    <code>.txPrimary</code>
                  </dd>
                  <dd>
                    <span>.text-danger</span>
                    <FaArrowRightLong />
                    <code>.txError</code>
                  </dd>
                </dl>
                <dl className={hs.instructionList}>
                  <dt>grid system</dt>
                  <dd>
                    <span>.col-6</span>
                    <FaArrowRightLong />
                    <code>.col6</code>
                  </dd>
                  <dd>
                    <span>.col-md-6</span>
                    <FaArrowRightLong />
                    <code>.col_md6</code>
                  </dd>
                  <dd>
                    <span>.row-cols-4</span>
                    <FaArrowRightLong />
                    <code>.rowCols4</code>
                  </dd>
                </dl>
              </IconContext.Provider>
            </div>
          </article>
          <article>
            <h2 className={hs.h2}>按鈕元件</h2>
            <dl className={hs.instructionList}>
              <dt>按鈕</dt>
              <dd>
                <span>.btn-primary</span>&emsp;
                <FaArrowRightLong />
                &emsp;
                <code
                  className={[hs.bgDark, hs.txSecondary].join(' ')}
                  style={{ padding: '.5rem' }}
                >
                  &lt;FddBtn href=&quot;#&quot;&gt;人家是按鈕&lt;/FddBtn&gt;
                </code>
                &emsp;
                <FaArrowRightLong />
                &emsp;
                <FddBtn href="#">人家是按鈕</FddBtn>
              </dd>
              <dd>
                <span>.btn-secondary</span>&emsp;
                <FaArrowRightLong />
                &emsp;
                <code
                  className={[hs.bgDark, hs.txSecondary].join(' ')}
                  style={{ padding: '.5rem' }}
                >
                  &lt;FddBtn color=&quot;secondary&quot; outline
                  callback=&#123;() =&gt;&#123;&#125;&#125;&gt;&lt;/FddBtn&gt;
                </code>
                &emsp;
                <FaArrowRightLong />
                &emsp;
                <FddBtn color="info" outline callback={() => {}}>
                  人家是按鈕
                </FddBtn>
              </dd>
              <dd>
                <span>.btn-secondary</span>&emsp;
                <FaArrowRightLong />
                &emsp;
                <code
                  className={[hs.bgDark, hs.txSecondary].join(' ')}
                  style={{ padding: '.5rem' }}
                >
                  &lt;FddBtn color=&quot;secondary&quot; icon callback=&#123;()
                  =&gt;&#123;&#125;&#125;&gt;&lt;/FddBtn&gt;
                </code>
                &emsp;
                <FaArrowRightLong />
                &emsp;
                <FddBtn color="error" icon callback={() => {}}>
                  <IoAddCircle />
                </FddBtn>
              </dd>
            </dl>
          </article>
          <article>
            <h2>
              <a
                href="https://react-icons.github.io/react-icons/"
                target="_blank"
                rel="noopener noreferrer"
              >
                React icons
              </a>
            </h2>
            <dl>
              <dt>小圖示的圖庫</dt>
              <dd>其大小會繼承該層的 font-size</dd>
              <dd>其顏色會繼承該層的 color</dd>
              <dd>若要手動改變，需要透過此 API 設計的 context</dd>
            </dl>
          </article>

          <h2 className={hs.h2}>常用連結</h2>
          <ul>
            <li>
              <span>小圖示庫：</span>
              <a
                href="https://react-icons.github.io/react-icons/"
                target="_blank"
                rel="noopener noreferrer"
              >
                React-icons
              </a>
            </li>
            <li>
              <span>專案 Figma：</span>
              <a
                href="https://www.figma.com/design/Q0KSE3JdYNKX3m1V2Hvnjf/fundodo-%E5%85%B1%E7%94%A8?node-id=93-69&t=E9X3RBeM4LSV4bUr-0"
                target="_blank"
                rel="noopener noreferrer"
              >
                React-icons
              </a>
            </li>
          </ul>
        </section>
      </main>
    </>
  );
}
