import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import NavHeader from '@/components/layout/navHeader';
import Hero from './Hero';
import ProdSec from './ProdSec';
import CourseSec from './CourseSec';
import HotelSec from './HotelSec';




export default function Homepage() {
  return (
    <>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavHeader />
      <Hero />
      <ProdSec />
      <CourseSec />
      <HotelSec />



    </>
  );
}
