import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import NavHeader from '@/components/layout/navHeader';
import Hero from './hero';
import Sec2 from './sec2';
// import Footer from '@/components/layout/default-layout/footer';



export default function Homepage() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavHeader />
      <Hero/>
      <Sec2/>
      {/* <Footer/> */}
      
    </>
  );
}
